#Modules

In [1]:
from py2neo import Graph, Node, Relationship

#Database

In [2]:
graph_db = Graph("http://neo4j:neo4ja@localhost:7474/db/data/",auth=("neo4j","neo4j"))

#Exploration

##Top 10 Ingredients

In [3]:
graph_db.run("MATCH (REC:Recipe)-[r:Contains]->(ING:Ingredient) WITH ING, count(r) AS num RETURN ING.Name as Name, num ORDER BY num DESC LIMIT 10;").to_data_frame()

            Name   num
0         Butter  9418
1         Cheese  9364
2        Chicken  9288
3         Cloves  9269
4       Cinnamon  9186
5  Baking Powder  8298
6      Chocolate  8227
7          Bread  7447
8    Baking Soda  6456
9           Beef  6436

##Top 10 Recipes with the biggest number of ingredients

In [4]:
graph_db.run("MATCH (REC:Recipe)-[r:Contains]->(ING:Ingredient) WITH REC, count(r) AS num RETURN REC.Name as Name, num ORDER BY num DESC LIMIT 10;").to_data_frame()

                                         Name  num
0                       Chicken Tortilla Soup   16
1                                  Fish Tacos   15
2                         Braised Lamb Shanks   15
3                            Hearty Beef Stew   14
4                                  Coq au Vin   14
5                                  Tamale Pie   13
6                         Mike's 3-Bean Chili   13
7                            hibernation fare   12
8                       Chicken and Dumplings   12
9  Spinach, Mushroom and Bacon Fondue (video)   12

##Spaghetti Bolognese

In [5]:
graph_db.run("MATCH (REC1:Recipe{Name:'Spaghetti Bolognese'})-[r:Contains]->(ING:Ingredient) RETURN REC1.Name, ING.Name;").to_data_frame()
#MATCH (n:Recipe{Name:'Spaghetti Bolognese'}) RETURN n

             REC1.Name    ING.Name
0  Spaghetti Bolognese      Cloves
1  Spaghetti Bolognese      Chives
2  Spaghetti Bolognese      Celery
3  Spaghetti Bolognese     Carrots
4  Spaghetti Bolognese       Bread
5  Spaghetti Bolognese  Beef Broth
6  Spaghetti Bolognese        Beef
7  Spaghetti Bolognese       Basil
8  Spaghetti Bolognese       Bacon

#Recommendation

##Add User

In [4]:
u = Node("User", Name="Ragnar")
UserNode = graph_db.merge(u,"User","Name")

##Add User likes

In [5]:
#UserRef = graph_db.match_one("User",property_key="Name", property_value="Ragnar")#look for user Ragnar
UserRef = graph_db.nodes.match("User", Name="Ragnar").first()

In [6]:
#RecipeRef = graph_db.find_one("Recipe",property_key="Name", property_value="Spaghetti Bolognese") #look for recipe Spaghetti Bolognese
RecipeRef=graph_db.nodes.match("Recipe", Name="Spaghetti Bolognese").first()
NodesRelationship = Relationship(UserRef, "Likes", RecipeRef) #Ragnar likes Spaghetti Bolognese
graph_db.create(NodesRelationship) #Commit his like to database

In [7]:
graph_db.create(Relationship(UserRef, "Likes", graph_db.nodes.match("Recipe",Name="Roasted Tomato Soup with Tiny Meatballs and Rice").first()))
graph_db.create(Relationship(UserRef, "Likes", graph_db.nodes.match("Recipe",Name="Moussaka").first()))
graph_db.create(Relationship(UserRef, "Likes", graph_db.nodes.match("Recipe",Name="Chipolata &amp; spring onion frittata").first()))
graph_db.create(Relationship(UserRef, "Likes", graph_db.nodes.match("Recipe",Name="Meatballs In Tomato Sauce").first()))
#graph_db.create(Relationship(UserRef, "Likes", graph_db.nodes.match("Recipe",Name="Macaroni cheese").first()))
#graph_db.create(Relationship(UserRef, "Likes", graph_db.nodes.match("Recipe",Name="Peppered Steak").first()))

##Recommend recipes to User

In [8]:
            graph_db.run("MATCH (USR1:User{Name:'Ragnar'})-[l1:Likes]->(REC1:Recipe),(REC1)-[c1:Contains]->(ING1:Ingredient) WITH  ING1,REC1 MATCH (REC2:Recipe)-[c2:Contains]->(ING1:Ingredient) WHERE REC1 <> REC2 RETURN REC2.Name,count(ING1) AS IngCount ORDER BY IngCount DESC LIMIT 40;").to_data_frame()

                                         REC2.Name  IngCount
0                             Italian Wedding Soup        16
1                              Reveillon Tourtiere        14
2                                 Hearty Beef Stew        14
3                          Spaghetti and Meatballs        14
4                              Braised Lamb Shanks        14
5                                French Onion Soup        14
6                               Braised Short Ribs        13
7                            Mexican Meatball Soup        13
8                                 Turkey Meatballs        13
9                         Spaghetti with Meatballs        13
10                                      Onion Soup        13
11         Philly Cheese  Steak French Bread Pizza        13
12  Grandma's Homemade Italian Sauce and Meatballs        13
13                                         Lasagna        13
14                       Spaghetti &amp; Meatballs        13
15                              Jamaican pepperpot        13
16                                      Albondigas        13
17                               Boeuf Bourguignon        12
18                                      Tamale Pie        12
19                                     My Meatloaf        12
20                            Crockpot Lentil Soup        12
21                                Cheeseburger Pie        12
22                               Cheeseburger Soup        12
23                              Teriyaki Meatballs        12
24                Beef Meatballs and Picante Glaze        12
25                        Juiciest Hamburgers Ever        12
26                               Italian Meatballs        12
27                                Italian Meatloaf        12
28                         Mexican Style Meatballs        12
29                                Simple Meatballs        12
30                                       Osso Buco        12
31                                 Stuffed Peppers        12
32                                       Meatballs        12
33                                   Pasta Fagioli        12
34                                      Pupu Balls        12
35                      Homemade Meatball Sandwich        12
36                       Joe's Favorite Hamburgers        12
37                                      Coq au vin        12
38                                         Lasagne        12
39                                         Bobotie        12